### ISSUE TITLE
4.6.0 runtime failure "Error: undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by ilovezfs** [defunkt/gist#263]
According to `git bisect` 4d9b012199560ca3e901705e3cdfd72a52890acc is the first bad commit.

```
bash-3.2$ echo homebrew | /usr/local/Cellar/gist/4.6.0/bin/gist   
Error: undefined method `[]' for nil:NilClass
```

Reverting 4d9b012199560ca3e901705e3cdfd72a52890acc makes the problem go away.

This was picked up by Homebrew CI for https://github.com/Homebrew/homebrew-core/pull/13629.

**Comment by ConradIrwin** [comment]
Thanks. I've reverted the netrc support for now, so 4.6.1 should work.

@biochimia — I apologise for not testing this code thoroughly before committing (it turns out through a bunch of subtle bugs it was differently broken on my machine and I didn't notice).

It turns out the `netrc` parser that we are using seems broken in that I cannot get it to correctly parse the following netrc file:

```
machine api.heroku.com
  password XXX
  login conrad.irwin@gmail.com
machine git.heroku.com
  password XXX
  login conrad.irwin@gmail.com
machine api.github.com
  password XXX
```

It returns api.github.com with a password of nil (and a login of XXX).

If we want to re-land netrc support, we will probably have to write our own parser or find one that does actually work/

**Comment by ilovezfs** [comment]
Thanks @ConradIrwin 

I've opened https://github.com/Homebrew/homebrew-core/pull/13641.

**Comment by biochimia** [comment]
Ouch!

And thanks for the heads up.

I'll give it another look and see what the issue is. Did I accidentally
switch user and password around, somehow?

Writing our own parser, if it comes to that, also shouldn't be a big deal.

**Comment by ConradIrwin** [comment]
Not sure, I think I was running into some variant of https://github.com/heroku/netrc/issues/14 — scanning through the code, it was hard to see the problem; a simpler parser would also be easier to debug :). 

Did the pull request work for you?

The actual bug that was reported was for people with no `.netrc` files — at which point `Netrc.read[...]` returns nil, and `Netrc.read[...][1]` crashes.

It turns out I had a netrc file with a `api.github.com` section already, and so when I tested it it appeared to work — I just didn't notice that the gist was created as an anonymous user.

The docs also suggest `machine github.com`, but I think you need to specify `machine api.github.com`.

**Comment by biochimia** [comment]
I tested netrc support in gist on its own as well as installed through brew, but only towards a Github Enterprise setup. For github.com, I was mostly relying on the `~/.gist` file. My file might have triggered the same bug heroky/netrc, but as I have the same token for different variations of the hostname, it wouldn't show.

I also did some very basic checks that `GITHUB_URL=gist.github.com` would work, but I guess I only used that endpoint anonymously.

I'll look at ressurrecting this feature with a custom parser and some sanity tests.
